packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: false
ignoredBuiltDependencies:
  - esbuild
  - sharp
