import { Metadata } from 'next';
import styles from './PageLayout.module.scss';

export type SearchSection = 'Website' | 'Documentation' | 'News' | 'Security' | 'Changelog';

interface PageLayoutProps {
  children: React.ReactNode;
  title?: string;
  description?: string;
  className?: string;
  // Section shown as a filter in the site search. Pagefind only indexes
  // elements marked data-pagefind-body, so the h1 and the content below are
  // what a search hit is made of; pass searchable={false} to keep a page out.
  searchSection?: SearchSection;
  searchable?: boolean;
}

export default function PageLayout({
  children,
  title,
  description,
  className = '',
  searchSection = 'Website',
  searchable = true,
}: PageLayoutProps) {
  const indexAttributes = searchable
    ? { 'data-pagefind-body': '', 'data-pagefind-filter': `section:${searchSection}` }
    : {};
  return (
    <div className={styles.pageContainer}>
      <div className={styles.container} {...indexAttributes}>
        {(title || description) && (
          <div className={styles.header}>
            {title && <h1>{title}</h1>}
            {description && <p className={styles.description}>{description}</p>}
          </div>
        )}
        <div className={`${styles.content} ${className}`}>{children}</div>
      </div>
    </div>
  );
}

interface PageMetadataOptions {
  // Open Graph locale of the page; the site default is English.
  locale?: 'en_US' | 'de_DE';
}

// Title and description for the document head and, with the same values, for
// the Open Graph and Twitter cards. Next.js replaces nested metadata objects
// instead of merging them, so the card fields set in the root layout would
// otherwise fall back to the homepage text on every page. For the same reason
// the card image, generated by src/app/opengraph-image.tsx and attached to the
// root layout automatically, has to be named here again.
const cardImage = { url: '/opengraph-image', width: 1200, height: 630, type: 'image/png' };

export function generatePageMetadata(title: string, description?: string, options: PageMetadataOptions = {}): Metadata {
  const fullTitle = `${title} - phpMyFAQ`;
  const text = description || `${title} - phpMyFAQ is a multilingual FAQ system`;
  return {
    title: fullTitle,
    description: text,
    openGraph: {
      type: 'website',
      siteName: 'phpMyFAQ',
      locale: options.locale ?? 'en_US',
      title: fullTitle,
      description: text,
      images: [{ ...cardImage, alt: fullTitle }],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description: text,
      images: [{ ...cardImage, alt: fullTitle }],
    },
  };
}