#!/usr/bin/env node

// Builds src/components/icons.generated.ts from the Font Awesome Free SVGs
// for every icon the site references, so the pages ship inline SVG instead
// of the 96 KB icon stylesheet and its webfonts.
//
// An icon is referenced as <Icon name="download" /> or icon: 'download' in a
// data array. Brand icons use the "brand-" prefix, e.g. "brand-github".
// Run `pnpm generate:icons` after adding an icon.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'src');
const faDir = path.join(root, 'node_modules', '@fortawesome', 'fontawesome-free', 'svgs');
const outFile = path.join(srcDir, 'components', 'icons.generated.ts');

function walk(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : entry.name.endsWith('.tsx') ? [full] : [];
  });
}

const names = new Set<string>();
const pattern = /(?:<Icon\b[^>]*\bname=|\bicon:\s*)["']([a-z0-9-]+)["']/g;
for (const file of walk(srcDir)) {
  if (file.endsWith('.test.tsx') || file.endsWith('.spec.tsx')) continue;
  const source = fs.readFileSync(file, 'utf8');
  for (const match of source.matchAll(pattern)) names.add(match[1]);
}

const icons: Record<string, { viewBox: string; path: string }> = {};
for (const name of [...names].sort()) {
  const brand = name.startsWith('brand-');
  const file = path.join(faDir, brand ? 'brands' : 'solid', `${brand ? name.slice(6) : name}.svg`);
  if (!fs.existsSync(file)) {
    console.error(`❌ No Font Awesome SVG for icon "${name}" (${file})`);
    process.exit(1);
  }
  const svg = fs.readFileSync(file, 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const d = svg.match(/<path[^>]*\bd="([^"]+)"/)?.[1];
  if (!viewBox || !d) {
    console.error(`❌ Could not parse ${file}`);
    process.exit(1);
  }
  icons[name] = { viewBox, path: d };
}

const body = Object.entries(icons)
  .map(([name, icon]) => `  '${name}': { viewBox: '${icon.viewBox}', path: '${icon.path}' },`)
  .join('\n');

fs.writeFileSync(
  outFile,
  `// Generated by scripts/generate-icons.ts. Do not edit by hand.
//
// Icons from Font Awesome Free (https://fontawesome.com), licensed under
// CC BY 4.0 (https://fontawesome.com/license/free). Copyright Fonticons, Inc.

export const icons = {
${body}
} as const;

export type IconName = keyof typeof icons;
`,
);

console.log(`✅ Wrote ${Object.keys(icons).length} icons to ${path.relative(root, outFile)}`);